version: '3.8'

services:

  gateway:
    container_name: nginx
    build:
      context: ./infra
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"  # Стандартный HTTP порт

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8001:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MATH_MODEL_URL=http://math_model:8002

  math_model:
    build: ./math_model
    container_name: math_model
    restart: always
    ports:
      - "8002:8002"

volumes:
  postgres_data: