version: '3.8'

services:

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  math_model:
    build: ./math_model
    container_name: math_model
    restart: always
    ports:
      - "8001:8001"

volumes:
  postgres_data: