version: '3.8'

services:

  gateway:
    container_name: nginx
    build:
      context: ./infra
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8001:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8001"

  math_model:
    build: ./math_model
    container_name: math_model
    restart: always
    ports:
      - "8002:8002"

  plc_service:
    build: ./PLCservice
    container_name: plc_service
    restart: always
    ports:
      - "8003:8003"

volumes:
  postgres_data: