version: '3.8'

services:

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: