"""Добавлено новое полÐе

Revision ID: 0aef45cced2b
Revises: 57bcd5ffb2a4
Create Date: 2025-10-21 12:03:28.713369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aef45cced2b'
down_revision: Union[str, None] = '57bcd5ffb2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_answers', sa.Column('model_answer', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_answers', 'model_answer')
    # ### end Alembic commands ###
